### ISSUE TITLE
Switch to CMake?

### ISSUE THREAD

**Issue by DavidZemon** [electrodude/esc#1]
If I do the hard part for you, would you be open to using CMake? This would give you easy access to IDEs like Eclipse and [CLion](https://www.jetbrains.com/clion/).

**Comment by DavidZemon** [comment]
To clarify, the "easy access" is because CLion reads CMake files directly and CMake will generate Eclipse project files. I know both Eclipse and CLion can be made to work with projects not already using CMake, but life is much easier if you switch to CMake.

**Comment by electrodude** [comment]
I've been considering switching to CMake since I started this, but I never got around to learning how to use it, and make has been good enough so far.  I'm not using any external libraries (yet), so it's not that big of a problem yet.  My IDE consists of vim, make, and gdb inside a tmux session, so IDE integration is pretty much meaningless to me (unless there's a vim cmake plugin), but I'm sure others (Windows users especially) would like to be able to use an IDE, and I'm also sure dependencies will get annoying soon, to the point that CMake becomes a necessity.  

If you do the hard work and then PR it, I'll merge it.  I'll probably do it myself later when I need to or when enough people ask for it, but otherwise it's low priority (for me at least) until it becomes a necessity.

**Comment by DavidZemon** [comment]
Cool. I'll get started on it. Shouldn't be hard since you don't have any dependencies yet :)

Also, take a look at [CLion](https://www.jetbrains.com/clion/) once I put in the PR. You'll love it. It's _worth_ using an IDE when said IDE is made by JetBrains.

**Comment by electrodude** [comment]
Closed by #2
